replicaCount: 2
image:
  repository: ghcr.io/thaolaptrinh/spatial-room-service
  tag: dev-latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  grpcPort: 9000
  mgmtPort: 9001
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
mtls:
  enabled: false
secretRef: room-service-secret
env:
  grpc__host: "0.0.0.0"
  grpc__port: "9000"
