#cloud-config
write_files:
  - path: /etc/rancher/k3s/config.yaml
    content: |
      tls-san:
        - "${server_private_ip}"
runcmd:
  - curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --cluster-init --token ${k3s_token}" sh -
  - chmod 644 /etc/rancher/k3s/k3s.yaml
