#cloud-config
write_files:
  - path: /etc/rancher/k3s/config.yaml
    content: |
      tls-san:
        - "${server_private_ip}"
runcmd:
  - curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --cluster-init" sh -
  - chmod 644 /etc/rancher/k3s/k3s.yaml
  - echo "K3S_TOKEN=$(cat /var/lib/rancher/k3s/server/node-token)" > /home/spatial/.k3s-join.env
