package room

import (
	"errors"
	"fmt"
	"time"

	"github.com/thaolaptrinh/spatial-server/internal/types"
)

// ErrNoCapacity is returned by an Allocator when no registered node can accept
// more work.
var ErrNoCapacity = errors.New("no runtime node with capacity")

// NodeDescriptor is the complete, platform-independent identity and runtime
// state of a Runtime Node.
//
// Identity is NodeID: an immutable UUIDv7 generated by the node at startup. It
// MUST NOT be derived from hostname, container name, service name, or IP —
// those are deployment details and not stable identities.
//
// AdvertiseAddr is the routable address (host:port) the deployment configures
// for reaching this node. Host/Port are retained only for backward-compatible
// reads from older registrations; Address() prefers AdvertiseAddr.
type NodeDescriptor struct {
	NodeID        types.ServerID
	AdvertiseAddr string
	Host          string // legacy raw host (back-compat)
	Port          int    // legacy raw port (back-compat)
	Version       string
	Build         string
	Capacity      NodeCapacity
	Load          NodeLoad
	Labels        map[string]string
	Status        types.ServerStatus
	StartTime     time.Time
	LastHeartbeat time.Time
}

// NodeCapacity declares a node's hard limits, consulted by allocators.
type NodeCapacity struct {
	MaxZones    int
	MaxEntities int // 0 = unlimited
}

// NodeLoad is the scheduling-relevant runtime state reported via heartbeat.
// It carries only what an allocator needs; it is intentionally not a general
// metrics dump (telemetry goes through the metrics endpoint).
type NodeLoad struct {
	ZoneCount      int
	ActiveEntities int
	ActiveSpaces   int
	ConnectedUsers int
	QueueDepth     int
	TickDurationMs float64
}

// Address returns the routable address of the node, preferring AdvertiseAddr
// and falling back to legacy host:port.
func (d *NodeDescriptor) Address() string {
	if d.AdvertiseAddr != "" {
		return d.AdvertiseAddr
	}
	return fmt.Sprintf("%s:%d", d.Host, d.Port)
}

// CanAccept reports whether the node can take on another zone right now.
func (d *NodeDescriptor) CanAccept() bool {
	if d.Status != types.ServerStatusActive {
		return false
	}
	if d.Capacity.MaxZones > 0 && d.Load.ZoneCount >= d.Capacity.MaxZones {
		return false
	}
	return true
}
