-- Clean PostgreSQL DDL for import. See imported.dbml (generated by the real importer).
CREATE TYPE order_status AS ENUM ('pending', 'paid', 'shipped');

CREATE TABLE customers (
  id serial PRIMARY KEY,
  email varchar(255) UNIQUE NOT NULL,
  created_at timestamp DEFAULT now()
);

CREATE TABLE orders (
  id serial PRIMARY KEY,
  customer_id integer NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  status order_status NOT NULL DEFAULT 'pending',
  total numeric(10,2)
);

CREATE INDEX idx_orders_customer ON orders(customer_id);

COMMENT ON TABLE orders IS 'Customer orders';
COMMENT ON COLUMN orders.status IS 'lifecycle state';
