services:
  game-server-1:
    build:
      context: ../..
      dockerfile: build/docker/game-server.Dockerfile
    hostname: game-server-1
    depends_on:
      postgres:
        condition: service_healthy
      room-service:
        condition: service_started
    environment:
      SPATIAL_GRPC__HOST: "game-server-1"
      SPATIAL_POSTGRES__DSN: "postgres://spatial:spatial@postgres:5432/spatial?sslmode=disable"
      SPATIAL_ROOM_SERVICE__ADDR: "room-service:9000"

  game-server-2:
    build:
      context: ../..
      dockerfile: build/docker/game-server.Dockerfile
    hostname: game-server-2
    depends_on:
      postgres:
        condition: service_healthy
      room-service:
        condition: service_started
    environment:
      SPATIAL_GRPC__HOST: "game-server-2"
      SPATIAL_POSTGRES__DSN: "postgres://spatial:spatial@postgres:5432/spatial?sslmode=disable"
      SPATIAL_ROOM_SERVICE__ADDR: "room-service:9000"
